global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using WebAppSpecExemple.Data;
global using WebAppSpecExemple.Dtos;
global using WebAppSpecExemple.Entites;
global using WebAppSpecExemple.Specifications;
global using WebAppSpecExemple.Utils;
global using MediatR;